title: Sablina Vis
show_downloads: true
# google_analytics: [Google Analytics tracking ID]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
